{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "boomi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "boomi.labels" . | nindent 4 }}
    app.kubernetes.io/component: boomi
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "boomi.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "boomi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}